{
 "title": "Dashboard Windows Exporter (ES)",
 "description": "Dashboard de Windows Exporter en espanol",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "interval", "label": "Intervalo", "query": "60s" },
   {
    "name": "server",
    "label": "Servidor",
    "query": "label_values(windows_cpu_time_total, instance)"
   }
  ]
 },
 "panels": [
  { "title": "Vistazo Rapido", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Tiempo activo",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 1 },
   "repeat": "server",
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "time() - windows_system_system_up_time{instance=~\"$server\"}"
    }
   ]
  },
  {
   "title": "Espacio Ocupado",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "windows_logical_disk_size_bytes{instance=~\"$server\",volume!~\"HarddiskVolume.+\",volume=~\".+\"} - windows_logical_disk_free_bytes{instance=~\"$server\",volume!~\"HarddiskVolume.+\",volume=~\".+\"}\r\n",
     "legendFormat": " {{volume}}"
    }
   ]
  },
  {
   "title": "Uso de disco",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(windows_logical_disk_size_bytes{volume!~\"Harddisk.*\", instance=\"$server\"}) by (instance) - sum(windows_logical_disk_free_bytes{volume!~\"Harddisk.*\", instance=\"$server\"}) by (instance)) / sum(windows_logical_disk_size_bytes{volume!~\"Harddisk.*\", instance=\"$server\"}) by (instance) * 100"
    }
   ]
  },
  {
   "title": "Memoria RAM Libre",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 9, "y": 1 },
   "repeat": "server",
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "clamp_min((1 - (windows_os_physical_memory_free_bytes{instance=~\"$server\"} / windows_os_visible_memory_bytes{instance=~\"$server\"})) * 100, 0)"
    }
   ]
  },
  {
   "title": "Uso de memoria",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(windows_os_visible_memory_bytes{instance=~\"$server\"} - windows_os_physical_memory_free_bytes{instance=~\"$server\"}) / windows_os_visible_memory_bytes{instance=~\"$server\"} * 100"
    }
   ]
  },
  {
   "title": "Espacio Disponible",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "windows_logical_disk_free_bytes{instance=~\"$server\",volume!~\"HarddiskVolume.+\",volume=~\".+\"}\r\n",
     "legendFormat": "{{volume}}"
    }
   ]
  },
  {
   "title": "Procesadores",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 4 },
   "repeat": "server",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count by (instance) (windows_cpu_time_total{instance=~\"$server\",mode=\"idle\"})"
    }
   ]
  },
  { "title": "CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Carga de CPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (mode) (rate(windows_cpu_time_total{instance=~\"$server\"}[5m]))",
     "legendFormat": "{{mode}}"
    }
   ]
  },
  {
   "title": "% de uso de CPU",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 9, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - (avg by (instance) (irate(windows_cpu_time_total{mode=\"idle\", instance=~\"$server\"}[1m])) * 100)"
    }
   ]
  },
  {
   "title": "Uso de CPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 13, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(avg without (cpu) (sum(irate(windows_cpu_time_total{instance=\"$server\",mode!=\"idle\"}[5m])) by (mode)) / 16)* 100",
     "legendFormat": "{{mode}}"
    }
   ]
  },
  { "title": "Discos duros", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Uso de discos",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 23, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - (windows_logical_disk_free_bytes{instance=~\"$server\",volume!~\"HarddiskVolume.+\",volume=~\".+\"} / windows_logical_disk_size_bytes{instance=~\"$server\",volume!~\"HarddiskVolume.+\",volume=~\".+\"}) * 100\r\n",
     "legendFormat": "{{volume}}"
    }
   ]
  },
  {
   "title": "Disco lectura/escritura",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "irate(windows_logical_disk_write_bytes_total{instance=~\"$server\", volume !~\"HarddiskVolume.+\"}[60s])",
     "legendFormat": "Write {{volume}}"
    },
    {
     "expr": "- irate(windows_logical_disk_read_bytes_total{instance=~\"$server\", volume !~\"HarddiskVolume.+\"}[60s])",
     "legendFormat": "Read {{volume}}"
    }
   ]
  },
  {
   "title": "Paquetes de red descartados/errores",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 11, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "irate(windows_net_packets_outbound_discarded_total{instance=~\"$server\"}[$interval]) + irate(windows_net_packets_outbound_errors_total{instance=~\"$server\"}[$interval])",
     "legendFormat": "Sent-Upload"
    },
    {
     "expr": "irate(windows_net_packets_received_discarded_total{instance=~\"$server\"}[$interval]) + irate(windows_net_packets_received_errors_total{instance=~\"$server\"}[$interval])",
     "legendFormat": "Received-Download"
    }
   ]
  },
  { "title": "Red", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 } },
  {
   "title": "Ancho de banda",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(windows_net_bytes_sent_total{instance=~\"$server\"}[$interval]) >0",
     "legendFormat": "Sent- Upload"
    },
    {
     "expr": "- rate(windows_net_bytes_received_total{instance=~\"$server\"}[$interval]) <0",
     "legendFormat": "Received- Download"
    }
   ]
  },
  {
   "title": "Ancho de banda",
   "type": "stat",
   "gridPos": { "h": 9, "w": 3, "x": 12, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(irate(windows_net_bytes_total{instance=\"$server\"}[1m])) > 1)* 8"
    }
   ]
  },
  {
   "title": "Operaciones E/S de disco",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 9, "x": 15, "y": 36 },
   "targets": [
    {
     "expr": "rate(windows_logical_disk_split_ios_total{instance=~\"$server\", volume !~\"HarddiskVolume.+\"}[60s])",
     "legendFormat": "i/o {{volume}}"
    }
   ]
  },
  {
   "title": "Flujo por hora",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(increase(windows_net_bytes_received_total{instance=\"$server\"}[1h])) by (instance)",
     "legendFormat": "Received-Download"
    },
    {
     "expr": "sum(increase(windows_net_bytes_sent_total{instance=\"$server\"}[1h])) by (instance)",
     "legendFormat": "Sent-Upload"
    }
   ]
  },
  {
   "title": "Otros",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 54 },
   "collapsed": true,
   "panels": [
    {
     "title": "Servicios por estado",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 9, "x": 0, "y": 55 },
     "targets": [
      {
       "expr": "count by (state) (windows_service_state{instance=~\"$server\"})",
       "legendFormat": "{{state}}"
      }
     ]
    },
    {
     "title": "Estado NTP (desfase)",
     "type": "stat",
     "gridPos": { "h": 7, "w": 3, "x": 9, "y": 55 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "time() - windows_os_time{instance=~\"$server\"}",
       "legendFormat": "{{ instance}}"
      }
     ]
    },
    {
     "title": "Procesos",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 55 },
     "targets": [
      {
       "expr": "windows_os_processes{instance=\"$server\"}",
       "legendFormat": "Processes"
      }
     ]
    },
    {
     "title": "SWAP total",
     "type": "stat",
     "gridPos": { "h": 8, "w": 4, "x": 0, "y": 62 },
     "fieldConfig": { "defaults": { "unit": "bps" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "windows_memory_swap_page_operations_total{instance=\"$server\"}",
       "legendFormat": "{{ instance }}"
      }
     ]
    },
    {
     "title": "Detalles de memoria",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 4, "y": 62 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "windows_cs_physical_memory_bytes{instance=~\"$server\"}",
       "legendFormat": "Physical memory"
      },
      {
       "expr": "windows_os_physical_memory_free_bytes{instance=~\"$server\"}",
       "legendFormat": "Free physical memory"
      },
      {
       "expr": "windows_os_virtual_memory_bytes{instance=~\"$server\"}",
       "legendFormat": "Virtual memory"
      },
      {
       "expr": "windows_os_virtual_memory_free_bytes{instance=~\"$server\"}",
       "legendFormat": "Free virtual memory"
      }
     ]
    },
    {
     "title": "Hilos del sistema",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 62 },
     "targets": [
      {
       "expr": "windows_system_threads{instance=~\"$server\"}",
       "legendFormat": "({{process}} threads) "
      }
     ]
    }
   ]
  }
 ]
}